language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - cp farnsworth/house_settings.py.example farnsworth/house_settings.py
  - echo "SECRET_KEY = 'TESTING SECRET KEY'" >> farnsworth/house_settings.py

# command to run tests
script:
  - coverage run --source=base,threads,events,managers,workshift,elections setup.py test

# command to notify coveralls
after_success:
  - coveralls
